### ISSUE TITLE
I need version GLIBC_2.29 of libc6 in MX Linux

### ISSUE THREAD

**Issue by mudgen** [MX-Linux/mx-system#7]
Hello,
I can't use the software I need to use with MX Linux because MX linux is using GLIBC_2.28 instead of GLIBC_2.29.   How can I get MX Linux to use GLIBC_2.29?  Or is there a way I can suggest that MX Linux add an update for GLIBC_2.29?  I am sorry if I am not asking in the right place, maybe you can direct me where to ask.

**Comment by dolphinoracle** [comment]
use mx21 instead of mx19.  mx21 uses 2.31. and this was not the right place to report this.  the forum would be the place for user support.

**Comment by mudgen** [comment]
Okay, thanks very much.
